### ISSUE TITLE
Switch from jsonrpc-core to jsonrpsee

### ISSUE THREAD

**Issue by ebkalderon** [ebkalderon/tower-lsp#102]
As previously described in #58, the [`jsonrpc-core`](https://github.com/paritytech/jsonrpc) crate is currently in maintenance mode and the [`jsonrpsee`](https://github.com/paritytech/jsonrpsee) crate is set to replace it in the future.

The `jsonrpc-core` has several design issues that make it less than ideal for our purposes, namely the dependency on old `futures` 0.1 and the lack of a bidirectional `stdio` transport, which is blocking #13 (see paritytech/jsonrpc#487 for details). `jsonrpsee` seems to have a much nicer API and is committed toward alleviating the existing crate's current structural issues.

As of pull request #101, we now support `std::future` and async/await through judicious use of `.compat()`, pervasive future boxing, a light dash of `Arc`s in a few places to keep `jsonrpc-core` happy. However, it would be nice to eliminate those hacks and work with an async/await native library such as `jsonrpsee`.

Unfortunately, `jsonrpsee` does not offer a `stdio` transport at all, much less one with bidirectional support, so we will have to wait until one is implemented upstream. Alternatively, if another JSON-RPC crate with equal or better ergonomics arises, we may switch `tower-lsp` to that instead.

**Comment by icsaszar** [comment]
This is really wishful thinking, but if I were to design a lsp crate, I would probably try to separate the transport part, the json-rpc part and the actual lsp logic part, similar to the TCP/IP model.

So in my opinion the ideal json-rpc handler would only:
- Given some input data (byte stream, input buffer) parse and dispatch notifications/requests and responses (similar to IoHandler)
- Given some input data (method parameters that implement Serialize) generate a request/notification into a buffer for the transport layer

Note that as discussed in #13, the json-rpc handler would have to be stateful (keep track of requests that have no response) to support responses, or provide an easy way for the user to access the request and response ids.

This way you could use any transport you like without any modifications to the rpc layer, which would be nice, since maybe somebody wants to run their language server over http, ipc or even ws.

**Comment by ebkalderon** [comment]
I agree with you, but that would ideally be a part of the underlying support from the JSON-RPC library in use rather than a custom implementation. Currently, `jsonrpc-core` natively supports bidirectional LSP RPC over TCP sockets and IPC by simply creating two `rpc` traits, one for the client-to-server interface and the other for the server-to-client interface. One would be instantiated with an `IoHandler` and the other with a `Client`, respectively. Imagine a scenario where the `Printer` contains an async `Client` and the `LspService` contains an `IoHandler` for the server. This would be ideal because both can operate independently and be agnostic over several different kinds of transports. Unfortunately, `stdio` is more complicated in that it doesn't fit that model. Instead, only one stdin/stdout connection is permitted and both client-to-server and server-to-client communication must be serialized and routed through this one set of pipes. They cannot operate independently. Because of this limitation, along with the lack of support by `jsonrpc-core` for a `stdio` client and the fact that most editors and IDEs support the `stdio` language server transport, I had to make some pragmatic sacrifices to get this library off the ground. I feel that we could get this to work by building a request router as described in #13, but this router is only really necessary for `stdio` transports, so either way, there will have to be some sacrifices.

**Comment by icsaszar** [comment]
In the end this (migrating from `jsonrpc-core`), along with #13 depends on what you want to do with this crate, given the current situation of being blocked on `jsonrpsee`.

To be completely transparent I need a language server library for a project I want to begin soon, so if you decide that the implementation is getting too hacky or a lot of the effort will go to waste on the rewrite I'll respect that (I really like and appreciate your attention to detail and quality standards, so it's completely understandable if you'd like to keep you public library clean). 

I'll try to help with whatever I can though, since I'll be working on the improvements I need (and I'm happy to consult with you so they can be integrated here too) in my fork anyway.

**Comment by ebkalderon** [comment]
I totally understand! And thank you for the kind words. I think it may be worth it to push forward on the request router in the short term, just so you can get started on your project, but keep in mind that we will be coupling closely to `stdio` if we decide to do this. I'm not sure if you intend to run your language server on other transports?

**Comment by icsaszar** [comment]
Thanks for helping me out!

I think I'll stick to stdio transport only, since (as you said) it's the most prominent.

**Comment by ebkalderon** [comment]
Sounds good! I think we'll move forward with the async channel-based request router while we are still relying on `jsonrpc-core` as the base JSON-RPC implementation. Perhaps if `jsonrpsee` gains a dedicated duplex `stdio` transport, we'll see if we can discard this router and be properly agnostic over the underlying transport method as well. Until then, `tower-lsp` is only targeting `stdio` out of the box.

**Comment by icsaszar** [comment]
I've just had a look at the issues in the `jsonrpsee` repo and there doesn't seem to be any issue opened for stdio transport (while there is for ipc and ws).

**Comment by ebkalderon** [comment]
Yeah, I'm guessing the `stdio` transport isn't as high of a priority. I would open an issue myself, but I also notice from the open and closed PRs that the design of `jsonrpsee` hasn't been fully set in stone yet, and I imagine we should let the API bake for a little longer before suggesting yet another (arguably more challenging) transport.

**Comment by ebkalderon** [comment]
It turns out it's actually been possible to use a TCP transport since PR #184! 🎉 @saskenuba was able to verify this in #196 with some clever usage of `tokio::net::TcpListener`. The documentation in `master` has been recently updated to reflect this in preparation for the next release. This experiment also confirms that the client-to-server and server-to-client traffic multiplexing logic already in `Server` works on both the `stdio` and TCP transports without a problem.

As such, I'm starting to think that switching to `jsonrpsee` might not even be necessary. From `jsonrpc-core`, we only depend on `IoHandler`, the `#[rpc]` proc macro, and some of the core JSON-RPC message and error types. We already have a generic transport, and the channel architecture of `jsonrpsee` doesn't seem to be a good match for LSP anyway. Perhaps we should instead ship a very minimal simplified subset of JSON-RPC specifically for `tower-lsp` that doesn't rely on external dependencies.

**Comment by ebkalderon** [comment]
I've instead opted to roll my own custom implementation in #202. Given that LSP has some unusual properties which don't neatly map to conventional JSON-RPC services (bidirectional communication multiplexed over a single stream/socket, a custom encoding scheme), I chose to ship a very minimal subset of JSON-RPC which integrates tightly with `lsp-types` and `serde` instead of relying on a generic JSON-RPC crate. It works pretty well, and it provides LSP-style request cancellation on top of that.
