### ISSUE TITLE
Consider re-exporting (a part of) jsonrpc_core to remove it as a dependency requirement

### ISSUE THREAD

**Issue by icsaszar** [ebkalderon/tower-lsp#108]
Both examples (`server.rs` and `custom_notification.rs`) import `jsonrpc_core` only for `jsonrpc_core::Result`. Perhaps it would be better to `pub use` `Result` and `Error` to not require it as a dependency, similar to `lsp_types` and `async_trait`.

**Comment by ebkalderon** [comment]
That's a good idea in theory, but I'm not sure whether we should re-export `Result` and/or `Error` under a different name, e.g. `RpcError`, to clarify that it's not our own error type. 🤔

**Comment by icsaszar** [comment]
`RpcError` is actually a good idea, since it suggests the layer (json-rpc) where the error will occur (here I mean that it's not the transport or lsp layer).

**Comment by ebkalderon** [comment]
I've come to the conclusion that it might not look as good in the `rustdoc` documentation to re-export `jsonrpc_core::Result` directly since it still shows the definition of the type alias as `Result<T, Error>` instead of `Result<T, RpcError>`. However, we could always define our own `Result` alias and expose that instead, which I think might be an even better option.

**Comment by ebkalderon** [comment]
Okay, so I've pushed a commit which re-exports `jsonrpc_core::{Error,Result}` without any renaming in the [`re-export-error-type`](https://github.com/ebkalderon/tower-lsp/tree/re-export-error-type) branch. Feel free to run `cargo doc` on your machine and evaluate how it looks.

I feel that having an `Error` type alongside `ExitedError` feels inconsistent, and I would prefer re-exporting the type as `RpcError` for that reason. However, `ExitedError` is not exposed directly to the user if they use `tower_lsp::Server` in their code, and I subjectively like the appearance of `Error::parse_error()` as opposed to `RpcError::parse_error()` in downstream user code.

Any thoughts on this, @icsaszar?

**Comment by icsaszar** [comment]
After thinking a bit about it, the only case where just renaming `Error` and `Result` helps is if you happen to have functions or methods in the same file that return `std::Result` or `Error` (from other crates), and even then you can reduce the scope of imports or just use something like `use jsonrpc_core as rpc` to solve the problem.

In the end I think it's fine as you implemented it on your branch. I think you shouldn't worry about `ExitedError` too much as it only comes up if you don't stick to the defaults (i.e. the `main` function from the examples).

**Comment by ebkalderon** [comment]
@icsaszar I propose another possible approach similar to your `jsonrpc_core as rpc` suggestion. I created a new branch named [`re-export-jsonrpc-types`](https://github.com/ebkalderon/tower-lsp/tree/re-export-jsonrpc-types) in which `jsonrpc_core::Result` and other common types are re-exported in a `jsonrpc` module. I like this approach a bit better because it re-exports only the necessary types and no more, keeping the API surface small to avoid potential breakage in the future. How does this look to you?

**Comment by icsaszar** [comment]
I just checked it out and I think it's ok. I agree with exposing a smaller API surface, since I think `Result` and `Error` are the only types that most of the users will need.

**Comment by ebkalderon** [comment]
Thanks for looking into it and giving your thoughts! I guess I'll merge it in and make a new release.
