### ISSUE TITLE
Can initialize be async as well?

### ISSUE THREAD

**Issue by sawmurai** [ebkalderon/tower-lsp#181]
Hello there!

I  am currently trying to implement a language server using this crate and ran into a problem:

The `InitializeParams` hold the `root_uri` of the current project (testing with VSCode). I need to somehow store this value to index all the relevant files in that folder, but since the `initialize` method is not async, I can not aqcuire a lock to a tokio Mutex to store that value somewhere. I have been fiddling around with `std::sync::Mutex` but ran into the blocker that I will later on not be able to send the value I stored behind it into a Future, as `std::sync::Mutex` does not implement the `Send` Trait. 

Maybe I am completely on the wrong path ... maybe you have an idea how to work around that issue? I assume `initialize` not being async has a reason ... if not ... maybe it could be changed to be async. 
I am rather new to Rust, so I might be missing something obvious, too.

**Comment by ebkalderon** [comment]
Good question! The reason why `initialize()` is not async is because the underlying [`jsonrpc-core`](https://github.com/paritytech/jsonrpc) library will treat handlers returning `Result` as blocking, refusing to accept any new requests until they have returned. It doesn't make much sense to allow the server to yield for more incoming requests while `initialize()` hasn't returned yet.

But now that you mention it, this might be a non-issue in practice. We already have an atomic mechanism for signaling whether the server has been initialized successfully or not, so turning `initialize()` into an asynchronous handler shouldn't be a problem. 🤔

**Comment by ebkalderon** [comment]
Either way, a well-behaving LSP client would wait until the `InitializeResult` has been received before sending subsequent requests, and a misbehaving LSP client would receive `-32002` "server not initialized" errors, as per the spec.

**Comment by sawmurai** [comment]
Great to hear :) and thank you for the explanation!

**Comment by ebkalderon** [comment]
@sawmurai I've opened #182 which should make this possible. I've tested the examples a little bit, and everything seems sensible.

**Comment by ebkalderon** [comment]
Done! I'll be aiming for a new release very soon.

**Comment by sawmurai** [comment]
Thanks a lot! This gets me unstuck.

**Comment by ebkalderon** [comment]
Thanks for the suggestion! ❤️ I'm currently looking into some apparent issues I'm experiencing with the client request routing. If I can fix that, I'll push out a new release as soon as I can.

**Comment by ebkalderon** [comment]
@sawmurai I've managed to fix #183, and there's a tiny bit more polishing to do, but you should expect a new release within a few hours. 😄

**Comment by ebkalderon** [comment]
@sawmurai Done! Should be out in [v0.11.0](https://github.com/ebkalderon/tower-lsp/releases/tag/v0.11.0).

**Comment by sawmurai** [comment]
Great! Just in time for the long weekend :) thank you
