### ISSUE TITLE
Improve Client ergonomics

### ISSUE THREAD

**Issue by Timmmm** [ebkalderon/tower-lsp#189]
Most callbacks provide a `client` parameter, but some don't (e.g. `goto_definition`). Is there a reason for that? It makes using the `client.log_message()` method awkward.

**Comment by ebkalderon** [comment]
Good question! There exists some historical context behind the current design. Basically, when I was prototyping the `LanguageServer` trait and `Client` struct, I wanted to grant the server access to the client where it was needed, but I also wanted to balance the complexity of trait method signatures and not have them be too verbose and unwieldy to type out by hand. As such, as a rule of thumb, I decided to grant `Client` access to all notification methods by default and piecemeal add in `Client` access to request methods where makes sense (e.g. `initialize` and `workspace/executeCommand`).

On one hand, I wouldn't mind amending the trait to grant `Client` access to more request methods (like `goto_definition`) if it makes language server authors' lives easier, like in your request, for example. But on the other hand, thanks to changes in #172, `Client` now implements `Clone`. I'm wondering if it would be possible not to pass in `Client` as an explicit argument to each individual method, but instead have it be passed in by move in `fn initialize()` and the server can store it inline as a struct field and used in whatever `LanguageServer` methods make sense to them.

Either way, some API design work and analysis of benefits vs. tradeoffs is necessary here, I think.

**Comment by ebkalderon** [comment]
Linking #188 here as a somewhat related topic of discussion.

**Comment by Timmmm** [comment]
> I'm wondering if it would be possible not to pass in Client as an explicit argument to each individual method, but instead have it be passed in by move in fn initialize() and the server can store it inline as a struct field and used in whatever LanguageServer methods make sense to them.

Seems reasonable to me!

**Comment by icsaszar** [comment]
The general problem here (and why I opened #188) is that if the `Client` gets initialized at runtime (in `initialized`) then you have to use something like `Option<Client>` (disregarding thread safety) for the code to compile, which makes using the `Client` a bit annoying.

My suggested solution would be have a wrapper type that implements `Deref` to `Client` and can be created without any parameters. Then it must be initialized in the `initialized` callback with a `Client` (or it can be something like `ClientInner` which would be an opaque wrapper around `Client` to prevent the usage without a wrapper), otherwise the methods will panic at runtime (a method to check if it's initialized could also be provided). This way we have the same ergonomic API and any number of such wrappers can exist, provided that they are initialized somewhere.

```rust
let wrapper = ClientWrapper::uninit();
assert!(wrapper.is_uninit());
wrapper.init(&client);
wrapper.show_message(...);
```

With this comment I think #188 can be probably closed to continue the discussion here.

**Comment by ebkalderon** [comment]
I think I may have an alternative approach. We could change `LspService::new()` to take an `FnOnce` rather than a server directly, like so:

```rust
#[derive(Debug)]
struct Backend {
    client: Client,
}

#[tower_lsp::async_trait]
impl LanguageServer for Backend {
    async fn initialize(&self, _: InitializeParams) -> Result<InitializeResult> {
        Ok(InitializeResult::default())
    }

    async fn initialized(&self, _: InitializedParams) {
        self.client.log_message(MessageType::Info, "server initialized!");
    }

    async fn shutdown(&self) -> Result<()> {
        Ok(())
    }
}

#[tokio::main]
async fn main() {
    let stdin = tokio::io::stdin();
    let stdout = tokio::io::stdout();

    let (service, messages) = LspService::new(|client| Backend { client });
    Server::new(stdin, stdout)
        .interleave(messages)
        .serve(service)
        .await;
}
```

This way, `Backend` can be initialized with a `client` field in a type-safe way without forcing the user to manually track the initialization state in their code. Additional resources can be initialized ahead of time in `main` and passed into the closure, if needed.

> With this comment I think #188 can be probably closed to continue the discussion here.

Good idea, @Timmmm! Let's consolidate the discussion here. I'll close the other issue and rename this one appropriately so we are all on the same page.

**Comment by ebkalderon** [comment]
I've opened #199 with an implementation of this, if anyone would like to review!
