### ISSUE TITLE
Serve on TCP over stdin

### ISSUE THREAD

**Issue by saskenuba** [ebkalderon/tower-lsp#196]
Is it possible to listen on TCP over stdin? I believe this would make the development a bit easier to follow.

Since Server takes an `AsyncRead + Unpin` I thought it would be simple, but it only answers the first message and the client hangs. I am still noobish with async rust, sorry.

Minimal example:
```rust
#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();

    let mut listener = tokio::net::TcpListener::bind("127.0.0.1:9001").await?;
    let (stream, _) = listener.accept().await?;

    let stdout = tokio::io::stdout();
    info!("Starting generic LSP Server..");

    let (service, messages) = LspService::new(Backend::default());

    Server::new(stream, stdout)
        .interleave(messages)
        .serve(service)
        .await;

    Ok(())
}
```

**Comment by ebkalderon** [comment]
Hey there, @saskenuba! Glad you're experimenting and learning with Rust. I should first point out that `tower-lsp` has never been tested and verified to work in TCP mode, only in the line-based `stdio` mode. There's no guarantee this will work as expected, as it's not yet supported.

With that said, I can see that your code is receiving requests from a `TcpStream` and routing requests to `stdout`, which I highly doubt is what you actually want to do. In fact, what you would want to do is to take the `TcpStream` and use [`tokio::io::split()`](https://docs.rs/tokio/0.2.22/tokio/io/fn.split.html) to split it into a read half and a write half, and pass them into the `Server` like this:

```rust
#[tokio::main]
async fn main() -> Result<()> {
    env_logger::init();

    let mut listener = tokio::net::TcpListener::bind("127.0.0.1:9001").await?;
    let (stream, _) = listener.accept().await?;
    let (read, write) = tokio::io::split(stream);

    info!("Starting generic LSP Server..");

    let (service, messages) = LspService::new(Backend::default());

    Server::new(read, write)
        .interleave(messages)
        .serve(service)
        .await;

    Ok(())
}
```

This should allow requests and responses to actually be routed properly over TCP. But as stated previously, the existing message flushing code was not built with TCP in mind, so I highly doubt this will work. I imagine a true TCP language server would instead have separate connections for client-to-server and server-to-client, rather than multiplexing messages over a single stream, like `stdio` does. It's just not supported by `tower-lsp` at this time.

You're more than welcome to submit pull requests, of course!

**Comment by saskenuba** [comment]
Hey, I can't believe I was passing stdout, no wonder the client couldn't read those messages, feeling stupid right now, haha.

After adjusting my code, even if not intended, it worked flawlessly over TCP! Thanks!

**Comment by ebkalderon** [comment]
That's fantastic news, @saskenuba! I'm glad to hear that `tower-lsp` works on TCP. Have you tried it in an editor that supports LSP over TCP?

Maybe we should update the included [example projects](https://github.com/ebkalderon/tower-lsp/tree/master/examples) to document that this works? We could rename `server.rs` to `stdio.rs`, and duplicate `stdio.rs` as `tcp.rs` and modify it to initialize with `TcpListener` as above.

**Comment by saskenuba** [comment]
Yes! I've used emacs with the [eglot](https://github.com/joaotavora/eglot) package. It offers an ad-hoc way of connecting to LSP servers, that supports both TCP and `stdio` with almost no configuration, except for host and port.

We really should do it, developing through TCP made it a whole lot easier than snooping file descriptors or logging into separate files.

**Comment by ebkalderon** [comment]
Sounds great! I was just able to verify that server-to-client notifications work as expected with [coc.nvim](https://github.com/neoclide/coc.nvim) and am about to verify server-to-client requests. On the examples side, I think we could rename `examples/server.rs` to `stdio.rs`, and then duplicate the file and name it `tcp.rs`, modifying it accordingly to work with `tokio::net::TcpListener`. Would you like to open a PR for that, @saskenuba? I'd be more than happy to review!

**Comment by ebkalderon** [comment]
Okay, I've created #198 to update and document how to use `tower-lsp` with a TCP transport. Thanks a ton for testing and validating `tower-lsp` on your end! I'm planning on releasing a new version to Crates.io soon with the updated documentation and other new features that have been quietly baking on `master` for a while now.
