### ISSUE TITLE
A dependency contains code that will be rejected by a future rust version

### ISSUE THREAD

**Issue by Calcoph** [ebkalderon/tower-lsp#359]
When compiling with rust v1.64 the following warning pops up:

`warning: the following packages contain code that will be rejected by a future version of Rust: ntapi v0.3.7`

`ntapi` is a dependency of `mio` which is a dependency of `tokio`.

This project uses tokio v1.17.0, I have tried another project and it doesn't throw any warnings with tokio v1.22.

**Comment by ebkalderon** [comment]
Thanks for the heads-up! Quite a few dependencies need to be updated in this repo, so perhaps I could put together a maintenance release.

**Comment by ebkalderon** [comment]
After some investigation, this dependency requirement isn't a risk and shouldn't matter. This project specifies a `tokio` version spec of `1.17` due to downstream dependencies, which is equivalent to `^1.17.0`. According to [the Cargo reference](https://doc.rust-lang.org/cargo/reference/specifying-dependencies.html), this means `tower-lsp` should work with all versions of `tokio` >2.0.0. The downstream user may `cargo update -p tokio` at any time to upgrade their `Cargo.lock` to the latest compatible version of `tokio` (1.24.1, at the time of writing). I don't believe there is anything directly actionable here on the `tower-lsp` side. Still, thanks for reporting!
