### ISSUE TITLE
Notification methods return Invalid request

### ISSUE THREAD

**Issue by tekumara** [ebkalderon/tower-lsp#388]
According to the spec processed [notification methods](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#notificationMessage) should not return a response.

But I've noticed notification methods return a response with the message "Invalid request" (as per [here](https://github.com/ebkalderon/tower-lsp/blob/afd0e33/src/jsonrpc/router.rs#L243)).

eg: a `textDocument/didOpen` request returns the response 
```json
{"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":2}
```

This took me by surprise and I've spent awhile trying to figure out if I have indeed made an invalid request 😅

**Comment by tekumara** [comment]
It's possible I'm doing something wrong here.. because my implementation of `did_open` doesn't actually seem to be called 🤔

**Comment by tekumara** [comment]
It's possible, that rather than being the client's fault,  I'm doing something wrong in the implementation of my language server, because my implementation of `did_open` doesn't actually seem to be called 🤔

**Comment by tekumara** [comment]
It's possible, that rather than being the client's fault in making an invalid request,  I'm doing something wrong in the implementation of my language server, because my implementation of `did_open` doesn't actually seem to be called 🤔

**Comment by tekumara** [comment]
It's possible I'm doing something wrong... Here's the full sequence of requests and responses:
```
2023-03-20T11:46:23.188414Z TRACE tower_lsp::codec: <- {"jsonrpc": "2.0","method": "initialize","params": {"capabilities": {"textDocumentSync": 1}},"id": 1}
2023-03-20T11:46:23.189896Z TRACE tower_lsp::codec: -> {"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":1},"serverInfo":{"name":"typos-lsp","version":"0.1.0"}},"id":1}
2023-03-20T11:46:23.190181Z TRACE tower_lsp::codec: <- {
                "jsonrpc": "2.0",
                "method": "textDocument/didOpen",
                "params": {
                  "textDocument": {
                    "uri": "file:///foo.rs",
                    "languageId": "rust",
                    "version": 1,
                    "text": "foobar"
                  }
                },
                "id": 2
              }
              2023-03-20T11:46:23.190374Z TRACE tower_lsp::codec: -> {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":2}
```

**Comment by tekumara** [comment]
It's possible I'm doing something wrong... Here's the full sequence of requests and responses:
```
2023-03-20T11:46:23.188414Z TRACE tower_lsp::codec: <- {"jsonrpc": "2.0","method": "initialize","params": {"capabilities": {"textDocumentSync": 1}},"id": 1}
2023-03-20T11:46:23.189896Z TRACE tower_lsp::codec: -> {"jsonrpc":"2.0","result":{"capabilities":{"textDocumentSync":1},"serverInfo":{"name":"typos-lsp","version":"0.1.0"}},"id":1}
2023-03-20T11:46:23.190181Z TRACE tower_lsp::codec: <- {
                "jsonrpc": "2.0",
                "method": "textDocument/didOpen",
                "params": {
                  "textDocument": {
                    "uri": "file:///foo.rs",
                    "languageId": "rust",
                    "version": 1,
                    "text": "foobar"
                  }
                },
                "id": 2
              }
2023-03-20T11:46:23.190374Z TRACE tower_lsp::codec: -> {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":2}
```

**Comment by ebkalderon** [comment]
Hi there, @tekumara! According to the JSON-RPC 2.0 spec, if an incoming message contains an `id` field, then is _not_ a notification but a request, and therefore a response must be sent back.

As seen in the quoted log output above:

> ```text
> 2023-03-20T11:46:23.190181Z TRACE tower_lsp::codec: <- {
>                 "jsonrpc": "2.0",
>                 "method": "textDocument/didOpen",
>                 "params": {
>                   "textDocument": {
>                     "uri": "file:///foo.rs",
>                     "languageId": "rust",
>                     "version": 1,
>                     "text": "foobar"
>                   }
>                 },
>                 "id": 2
>               }
> 2023-03-20T11:46:23.190374Z TRACE tower_lsp::codec: -> {"jsonrpc":"2.0","error":{"code":-32600,"message":"Invalid request"},"id":2}
> ```

The `textDocument/didOpen` message is being sent with an `id` key with a value of `2`, making this a request message. However, since the `textDocument/didOpen` method is registered on the server as a notification and not a request, the server responds with an `Invalid request` message indicating that the method has been called improperly. Does this make sense?

**Comment by ebkalderon** [comment]
I thought I'd leave a TL;DR here, in addition to the above two responses. In short, the `textDocument/didOpen` method is indeed registered as a notification on the server side, but the incoming message shown in the trace logs contains an `"id"` field. That field is expected for request objects only, and `textDocument/didOpen` is a notification method. The server is obligated to respond to _all_ incoming request object with a corresponding response object (as per the spec), so it responds with an error. This is expected behavior for all JSON-RPC and LSP servers ([for reference, `clangd` behaves exactly the same way](https://stackoverflow.com/questions/74203637/why-does-clangd-respond-with-method-not-found-when-using-textdocument-didopen)).

Removing the unexpected `"id"` field from the message should fix the specific error you're seeing. Hope this helps! :+1:

**Comment by tekumara** [comment]
Oh I see! Thank you for walking me through that. It does indeed work when I remove the `id` field in the request. 🤭

**Comment by ebkalderon** [comment]
No worries. Glad you found the explanation helpful! The JSON-RPC 2.0 protocol (the base upon which LSP sits) is poorly specified in several key areas, IMO. I've found that some level of confusion and surprise is inevitable when interpreting the official spec, haha. To date, I've found that fuzzing the most popular JSON-RPC implementations in the wild and mimicking their behavior in `tower-lsp` has been just as instructive as reading the official spec, if not more so. Hope this assists your debugging efforts going forward! :smile:
